### ISSUE TITLE
Adding elements outside an htsd-slide

### ISSUE THREAD

**Issue by soelen** [tkareine/hackers-tiny-slide-deck#4]
Good day,

it seems that htsd tries to reattach elements in htsd-slides.

Is there something I can do about it? For example I created a custom component called wm-workbox, wheter I put if at the beginning, before, after or at the end of a body tag htsd tries to put it into a slide.

![image](https://user-images.githubusercontent.com/1114549/151957604-cce84bfa-7fbb-4cb8-a2af-e4b3ea1e64e4.png)

Thanks in advance!

**Comment by tkareine** [comment]
When HTSD installs slides, it wraps elements inside the `<body>` tag into `<div>`s. The `<hr>` tag marks the beginning of the next slide. This behavior is designed for html files generated from Markdown files in mind.

I don't know how you've generated or written the html file in which you want to install HTSD, but maybe creating html elements dynamically is an option for you. If so, then you can proceed as follows:

1. Add a template tag somewhere in the html document
2. Embed the HTSD script into the document with the `data-manual` attribute (this prevents the automatic installation of slides)
3. Add a script that installs HTSD slides manually and inserts new elements into the document based on the contents of the template

For example, you can append the following in the end of a Markdown document:

```html
<script type="text/javascript" src="htsd.min.js" data-manual></script>
<script type="text/template" id="my-template">
  <div>hidden content</div>
</script>
<script type="text/javascript">
  window.htsd.installAll()
  const templateStr = document.getElementById("my-template").innerText.trim()
  const templateNode = document.createElement("template")
  templateNode.innerHTML = templateStr
  document.querySelector("body").appendChild(templateNode.content.firstChild)
</script>
```

Once you load that, you should see that `<div>hidden content</div>` is the last child element of `<body>`.

Also, you can replace `<script type="text/template" id="my-template">` with `<template id="my-template">`, giving you a document fragment ready to be used. That would allow omitting the `document.createElement("template")` call in step 3. Unfortunately, the `marked` Markdown compiler wraps a `<template>` tag within a `<p>` tag.

**Comment by soelen** [comment]
Thank you for the quick and helpful response tkareine
